### PR TITLE
Feature: Chat stream response

### PR DESCRIPTION
**Pull request by devcxl**
Hello, I tried to add streaming return functionality, but it seems it doesn't truly stream the return. Can you help me take a look at this piece of code?

### CODE REVIEW

**Comment by devcxl** [comment]
```
$ curl http://localhost:8787/v1/chat/completions   -H "Content-Type: application/json"   -H "Authorization: Bearer sk-123123123123123"   -d '{
    "stream":true,
    "model": "@cf/qwen/qwen1.5-0.5b-chat",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello"
      }
    ]
  }'
data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":"Hello"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":"!"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":" How"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":" may"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":" I"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":" assist"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":" you"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":" today"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":"?"},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":""},"index":0,"finish_reason":null}]}

data: {"id":"ed370b7a-c20d-46f2-a553-0d8d71caf336","created":1712475793,"object":"chat.completion.chunk","model":"@cf/qwen/qwen1.5-0.5b-chat","choices":[{"delta":{"content":""},"index":0,"finish_reason":"stop"}]}
```

I tested the return like this, and it conforms to the format of streaming return. However, it seems to return all the data at once.

**Comment by chand1012** [comment]
I'll definitely take a look, this is a needed feature.

**Comment by devcxl** [comment]
The answer from ChatGPT is not reliable. I tried to split the TransformStream into readable and writable parts, then returned the readable part, but the result still seems to return all the results at once.

```js
			const { readable,writable} = new TransformStream({
				// omit some code
			});

			// for now, nothing else does anything. Load the ai model.
			const aiResp = await ai.run(model, { stream: json.stream, messages });
			// Piping the readableStream through the transformStream

			aiResp.pipeTo(writable)
			return json.stream ? new Response(readable, {
				headers: {
					'content-type': 'text/event-stream',
					'Cache-Control': 'no-cache',
					'Connection': 'keep-alive',
				},
			})

```

**Comment by chand1012** [comment]
Your above code seems to work on my side, how are you testing this? Here is now I tested the streaming.
```bash
curl -H 'Content-Type: application/json' -d '{
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant"
    },
    {
      "role": "user",
      "content": "Write me an essay on the formation of black holes"
    }
  ],
  "stream": true
}' http://localhost:8787/chat/completions
```
And it seemed to work fine. Another thing that should be updated is [here](https://github.com/devcxl/openai-cf-workers-ai/blob/b85c2ab546c0f2a0938e073110c1de0001279c66/wrangler.toml#L3). On my branch (linked below) I had to update the version to the latest version (`2024-04-05` as of today) in order to get everything working properly.

I pushed the code to a [separate branch for testing](https://github.com/chand1012/openai-cf-workers-ai/compare/main...chand1012/streaming), however I intend to merge this PR and delete that branch once the code is working.

**Comment by devcxl** [comment]
"Upgrading compatibility_date without using compatibility_flags is also possible."

**Comment by chand1012** [comment]
Thank you for your contribution!

**Pull request merged**
